-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-01-16 12:23:58 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE asocjacja_stanowiska (
    stanowisko_id_stanowiska NUMBER(10) NOT NULL,
    pracownik_id_prac        NUMBER(10) NOT NULL
);

ALTER TABLE asocjacja_stanowiska ADD CONSTRAINT relation_5_pk PRIMARY KEY ( stanowisko_id_stanowiska,
                                                                            pracownik_id_prac );

CREATE TABLE "asocjacja podwladnego" (
    pracownik_id_prac  NUMBER(10) NOT NULL,
    pracownik_id_prac1 NUMBER(10) NOT NULL
);

ALTER TABLE "asocjacja podwladnego" ADD CONSTRAINT relation_6_pk PRIMARY KEY ( pracownik_id_prac,
                                                                               pracownik_id_prac1 );

CREATE TABLE asoscjacja_magazynu (
    towar_id_produktu   NUMBER(10) NOT NULL,
    magazyn_id_magazynu NUMBER(10) NOT NULL
);

ALTER TABLE asoscjacja_magazynu ADD CONSTRAINT relation_27_pk PRIMARY KEY ( towar_id_produktu,
                                                                            magazyn_id_magazynu );

CREATE TABLE asoscjacja_placy (
    umowa_pracownika_id_umowy NUMBER(10) NOT NULL,
    placa_id_placy            NUMBER(12) NOT NULL
);

ALTER TABLE asoscjacja_placy ADD CONSTRAINT relation_17_pk PRIMARY KEY ( umowa_pracownika_id_umowy,
                                                                         placa_id_placy );

CREATE TABLE asoscjacja_poziomu_znajomosci ( 
--  ERROR: Column name length exceeds maximum allowed length(30) 
    poziom_znajomosci_jezyka_id_znajomosci_jezyka NUMBER(10) NOT NULL,
    jezyk_id_jezyka                               NUMBER(10) NOT NULL
);

ALTER TABLE asoscjacja_poziomu_znajomosci ADD CONSTRAINT relation_26_pk PRIMARY KEY ( poziom_znajomosci_jezyka_id_znajomosci_jezyka,
                                                                                      jezyk_id_jezyka );

CREATE TABLE asoscjacja_wyksztalcenia (
    pracownik_id_prac              NUMBER(10) NOT NULL,
    wyksztalcenie_id_wyksztalcenia NUMBER(10) NOT NULL
);

ALTER TABLE asoscjacja_wyksztalcenia ADD CONSTRAINT relation_1_pk PRIMARY KEY ( pracownik_id_prac,
                                                                                wyksztalcenie_id_wyksztalcenia );

CREATE TABLE assoscjacja_benefitu (
    stanowisko_id_stanowiska NUMBER(10) NOT NULL,
    benefit_id_benefitu      NUMBER(10) NOT NULL
);

ALTER TABLE assoscjacja_benefitu ADD CONSTRAINT relation_9_pk PRIMARY KEY ( stanowisko_id_stanowiska,
                                                                            benefit_id_benefitu );

CREATE TABLE benefit (
    id_benefitu NUMBER(10) NOT NULL,
    nazwa       VARCHAR2(50) NOT NULL,
    koszt       NUMBER(10, 2) NOT NULL,
    poziom      VARCHAR2(50)
);

ALTER TABLE benefit ADD CONSTRAINT benefit_pk PRIMARY KEY ( id_benefitu );

CREATE TABLE dzial (
    id_dzialu               NUMBER(10) NOT NULL,
    nazwa                   VARCHAR2(50) NOT NULL,
    adres                   VARCHAR2(100) NOT NULL,
    kirownik_dzialu_id_prac NUMBER(10) NOT NULL
);

ALTER TABLE dzial ADD CONSTRAINT dzial_pk PRIMARY KEY ( id_dzialu );

CREATE TABLE faktura (
    id_faktury                            NUMBER(10) NOT NULL,
    data_wystawienia_faktury              DATE NOT NULL,
    data_platnosci                        DATE NOT NULL,
    typ_faktury                           VARCHAR2(50) NOT NULL,
    rodzaj_platnosci                      VARCHAR2(100) NOT NULL,
    wartosc_netto                         NUMBER(10, 2) NOT NULL,
    wartosc_brutto                        NUMBER(10, 2) NOT NULL,
    kontrachent_id_kontrachenta           NUMBER(10),
    pracownik_id_prac                     NUMBER(10) NOT NULL, 
--  ERROR: Column name length exceeds maximum allowed length(30) 
    ksiega_przychodu_i_rozchodu_id_ksiegi NUMBER(10)
);

ALTER TABLE faktura ADD CONSTRAINT faktura_pk PRIMARY KEY ( id_faktury );

CREATE TABLE jezyk (
    id_jezyka NUMBER(10) NOT NULL,
    nazwa     VARCHAR2(50) NOT NULL,
    podtyp    VARCHAR2(50)
);

ALTER TABLE jezyk ADD CONSTRAINT jezyk_pk PRIMARY KEY ( id_jezyka );

CREATE TABLE kirownik_dzialu (
    id_prac                      NUMBER(10) NOT NULL,
    numer_telefonu_stacjonarnego VARCHAR2(20) NOT NULL
);

ALTER TABLE kirownik_dzialu ADD CONSTRAINT kirownik_dzialu_pk PRIMARY KEY ( id_prac );

CREATE TABLE kontrachent (
    id_kontrachenta         NUMBER(10) NOT NULL,
    nazwa                   VARCHAR2(200) NOT NULL,
    adres_siedziby          VARCHAR2(100) NOT NULL,
    nip                     NUMBER(12) NOT NULL,
    adres_do_korespondencji VARCHAR2(100) NOT NULL,
    czy_czynny_podatnik_vat CHAR(1) NOT NULL
);

ALTER TABLE kontrachent ADD CONSTRAINT kontrachent_pk PRIMARY KEY ( id_kontrachenta );

CREATE TABLE koszt_zus (
    id_kosztu_zus      NUMBER(10) NOT NULL,
    okres              VARCHAR2(100) NOT NULL,
    skladka_zdrowotna  NUMBER(10, 2) NOT NULL,
    skladka_emerytalna NUMBER(10, 2) NOT NULL,
    skladka_rentowa    NUMBER(10, 2) NOT NULL,
    skladka_chorobowa  NUMBER(10, 2) NOT NULL,
    skladka_wypadkowa  NUMBER(10, 2) NOT NULL,
    fundusz_pracy      NUMBER(10, 2) NOT NULL
);

ALTER TABLE koszt_zus ADD CONSTRAINT koszt_zus_pk PRIMARY KEY ( id_kosztu_zus );

CREATE TABLE ksiega_przychodu_i_rozchodu (
    id_ksiegi               NUMBER(10) NOT NULL,
    okres                   VARCHAR2(100) NOT NULL,
    data_stworzenia         DATE NOT NULL,
    kto_stworzyl            VARCHAR2(50) NOT NULL,
    koszt_zus_id_kosztu_zus NUMBER(10) NOT NULL
);

ALTER TABLE ksiega_przychodu_i_rozchodu ADD CONSTRAINT ksiega_przychodu_i_rozchodu_pk PRIMARY KEY ( id_ksiegi );

CREATE TABLE magazyn (
    id_magazynu NUMBER(10) NOT NULL,
    nazwa       VARCHAR2(50) NOT NULL,
    adres       VARCHAR2(200) NOT NULL
);

ALTER TABLE magazyn ADD CONSTRAINT magazyn_pk PRIMARY KEY ( id_magazynu );

CREATE TABLE placa (
    id_placy                              NUMBER(12) NOT NULL,
    liczba_przepracowanych_godzin         NUMBER(10) NOT NULL,
    dodatki                               NUMBER(10, 2),
    nadgodziny                            NUMBER(10),
    ostateczna_kwota                      NUMBER(10, 2) NOT NULL, 
--  ERROR: Column name length exceeds maximum allowed length(30) 
    ksiega_przychodu_i_rozchodu_id_ksiegi NUMBER(10)
);

ALTER TABLE placa ADD CONSTRAINT placa_pk PRIMARY KEY ( id_placy );

CREATE TABLE poziom_znajomosci_jezyka (
    id_znajomosci_jezyka NUMBER(10) NOT NULL,
    nazwa                VARCHAR2(50)
);

ALTER TABLE poziom_znajomosci_jezyka ADD CONSTRAINT poziom_znajomosci_jezyka_pk PRIMARY KEY ( id_znajomosci_jezyka );

CREATE TABLE pracownik (
    id_prac               NUMBER(10) NOT NULL,
    imie                  VARCHAR2(50) NOT NULL,
    nazwisko              VARCHAR2(50) NOT NULL,
    data_urodzenia        DATE NOT NULL,
    pesel                 NUMBER(11),
    plec                  VARCHAR2(2),
    drugie_imie           VARCHAR2(50),
    nazwisko_rodowe       VARCHAR2(50),
    numer_konta_bankowego NUMBER(50),
    dzial_id_dzialu       NUMBER(10) NOT NULL,
    adres                 VARCHAR2(100)
);

ALTER TABLE pracownik ADD CONSTRAINT pracownik_pk PRIMARY KEY ( id_prac );

CREATE TABLE produkt (
    id_produktu        NUMBER(10) NOT NULL,
    nazwa              VARCHAR2(100) NOT NULL,
    cena_netto         NUMBER(10, 2) NOT NULL,
    faktura_id_faktury NUMBER(10) NOT NULL
);

ALTER TABLE produkt ADD CONSTRAINT produkt_pk PRIMARY KEY ( id_produktu );

CREATE TABLE relation_7 (
    stanowisko_id_stanowiska   NUMBER(10) NOT NULL,
    uprawnienia_id_uprawnienia NUMBER(10) NOT NULL
);

ALTER TABLE relation_7 ADD CONSTRAINT relation_7_pk PRIMARY KEY ( stanowisko_id_stanowiska,
                                                                  uprawnienia_id_uprawnienia );

CREATE TABLE rodzaj_towarow (
    id_rodzaju_towaru   NUMBER(10) NOT NULL,
    nazwa               VARCHAR2(100) NOT NULL,
    stawka_vat          NUMBER(10, 2) NOT NULL,
    produkt_id_produktu NUMBER(10) NOT NULL
);

ALTER TABLE rodzaj_towarow ADD CONSTRAINT rodzaj_towarow_pk PRIMARY KEY ( id_rodzaju_towaru,
                                                                          stawka_vat );

CREATE TABLE stanowisko (
    id_stanowiska NUMBER(10) NOT NULL,
    nazwa         VARCHAR2(50) NOT NULL
);

ALTER TABLE stanowisko ADD CONSTRAINT stanowisko_pk PRIMARY KEY ( id_stanowiska );

CREATE TABLE srodek_trwaly (
    id_produktu        NUMBER(10) NOT NULL,
    stawka_amortyzacji VARCHAR2(100)
);

ALTER TABLE srodek_trwaly ADD CONSTRAINT srodek_trwaly_pk PRIMARY KEY ( id_produktu );

CREATE TABLE towar (
    id_produktu                                   NUMBER(10) NOT NULL,
    data_przyjecia_na_stan                        DATE,
    data_zbycia                                   DATE, 
--  ERROR: Column name length exceeds maximum allowed length(30) 
    czy_wrzucamy_go_do_ewidencji_srodkow_trwalych CHAR(1)
);

ALTER TABLE towar ADD CONSTRAINT towar_pk PRIMARY KEY ( id_produktu );

CREATE TABLE umowa_pracownika (
    id_umowy                     NUMBER(10) NOT NULL,
    rodzaj_umowy                 VARCHAR2(50) NOT NULL,
    data_zawarcia                DATE NOT NULL,
    data_zakonczenia             DATE,
    rodzaj_zatrudnienia          VARCHAR2(50) NOT NULL,
    wielkosc_etatu               VARCHAR2(50) NOT NULL,
    stawka_godzinowa             NUMBER(10, 2),
    zatrudnienie_zatrudnienie_id NUMBER NOT NULL
);

ALTER TABLE umowa_pracownika ADD CONSTRAINT umowa_pracownika_pk PRIMARY KEY ( id_umowy );

CREATE TABLE uprawnienia (
    id_uprawnienia NUMBER(10) NOT NULL,
    nazwa          VARCHAR2(50) NOT NULL
);

ALTER TABLE uprawnienia ADD CONSTRAINT uprawnienia_pk PRIMARY KEY ( id_uprawnienia );

CREATE TABLE usluga (
    id_produktu        NUMBER(10) NOT NULL,
    data_zrealizowania DATE
);

ALTER TABLE usluga ADD CONSTRAINT usluga_pk PRIMARY KEY ( id_produktu );

CREATE TABLE wyksztalcenie (
    id_wyksztalcenia NUMBER(10) NOT NULL,
    poziom           VARCHAR2(50) NOT NULL,
    nazwa            VARCHAR2(100) NOT NULL,
    data_uzyskania   DATE NOT NULL,
    ukonczona_szkola VARCHAR2(100) NOT NULL,
    podtyp           VARCHAR2(100)
);

ALTER TABLE wyksztalcenie ADD CONSTRAINT wyksztalcenie_pk PRIMARY KEY ( id_wyksztalcenia );

CREATE TABLE zatrudnienie (
    data_rozpoczecia DATE NOT NULL,
    data_zakonczenia DATE,
    zatrudnienie_id  NUMBER NOT NULL
);

ALTER TABLE zatrudnienie ADD CONSTRAINT zatrudnienie_pk PRIMARY KEY ( zatrudnienie_id );

CREATE TABLE zatrudnieniev1 (
    pracownik_id_prac            NUMBER(10) NOT NULL,
    zatrudnienie_zatrudnienie_id NUMBER NOT NULL
);

ALTER TABLE zatrudnieniev1 ADD CONSTRAINT zatrudnieniev1_pk PRIMARY KEY ( pracownik_id_prac,
                                                                          zatrudnienie_zatrudnienie_id );

CREATE TABLE znajomosc_jezyka (
    pracownik_id_prac NUMBER(10) NOT NULL,
    jezyk_id_jezyka   NUMBER(10) NOT NULL
);

ALTER TABLE znajomosc_jezyka ADD CONSTRAINT znajomosc_jezyka_pk PRIMARY KEY ( pracownik_id_prac,
                                                                              jezyk_id_jezyka );

ALTER TABLE dzial
    ADD CONSTRAINT dzial_kirownik_dzialu_fk FOREIGN KEY ( kirownik_dzialu_id_prac )
        REFERENCES kirownik_dzialu ( id_prac );

ALTER TABLE faktura
    ADD CONSTRAINT faktura_kontrachent_fk FOREIGN KEY ( kontrachent_id_kontrachenta )
        REFERENCES kontrachent ( id_kontrachenta );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE faktura
    ADD CONSTRAINT faktura_ksiega_przychodu_i_rozchodu_fk FOREIGN KEY ( ksiega_przychodu_i_rozchodu_id_ksiegi )
        REFERENCES ksiega_przychodu_i_rozchodu ( id_ksiegi );

ALTER TABLE faktura
    ADD CONSTRAINT faktura_pracownik_fk FOREIGN KEY ( pracownik_id_prac )
        REFERENCES pracownik ( id_prac );

ALTER TABLE kirownik_dzialu
    ADD CONSTRAINT kirownik_dzialu_pracownik_fk FOREIGN KEY ( id_prac )
        REFERENCES pracownik ( id_prac );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE ksiega_przychodu_i_rozchodu
    ADD CONSTRAINT ksiega_przychodu_i_rozchodu_koszt_zus_fk FOREIGN KEY ( koszt_zus_id_kosztu_zus )
        REFERENCES koszt_zus ( id_kosztu_zus );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE placa
    ADD CONSTRAINT placa_ksiega_przychodu_i_rozchodu_fk FOREIGN KEY ( ksiega_przychodu_i_rozchodu_id_ksiegi )
        REFERENCES ksiega_przychodu_i_rozchodu ( id_ksiegi );

ALTER TABLE pracownik
    ADD CONSTRAINT pracownik_dzial_fk FOREIGN KEY ( dzial_id_dzialu )
        REFERENCES dzial ( id_dzialu );

ALTER TABLE produkt
    ADD CONSTRAINT produkt_faktura_fk FOREIGN KEY ( faktura_id_faktury )
        REFERENCES faktura ( id_faktury );

ALTER TABLE asoscjacja_wyksztalcenia
    ADD CONSTRAINT relation_1_pracownik_fk FOREIGN KEY ( pracownik_id_prac )
        REFERENCES pracownik ( id_prac );

ALTER TABLE asoscjacja_wyksztalcenia
    ADD CONSTRAINT relation_1_wyksztalcenie_fk FOREIGN KEY ( wyksztalcenie_id_wyksztalcenia )
        REFERENCES wyksztalcenie ( id_wyksztalcenia );

ALTER TABLE asoscjacja_placy
    ADD CONSTRAINT relation_17_placa_fk FOREIGN KEY ( placa_id_placy )
        REFERENCES placa ( id_placy );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE asoscjacja_placy
    ADD CONSTRAINT relation_17_umowa_pracownika_fk FOREIGN KEY ( umowa_pracownika_id_umowy )
        REFERENCES umowa_pracownika ( id_umowy );

ALTER TABLE asoscjacja_poziomu_znajomosci
    ADD CONSTRAINT relation_26_jezyk_fk FOREIGN KEY ( jezyk_id_jezyka )
        REFERENCES jezyk ( id_jezyka );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE asoscjacja_poziomu_znajomosci
    ADD CONSTRAINT relation_26_poziom_znajomosci_jezyka_fk FOREIGN KEY ( poziom_znajomosci_jezyka_id_znajomosci_jezyka )
        REFERENCES poziom_znajomosci_jezyka ( id_znajomosci_jezyka );

ALTER TABLE asoscjacja_magazynu
    ADD CONSTRAINT relation_27_magazyn_fk FOREIGN KEY ( magazyn_id_magazynu )
        REFERENCES magazyn ( id_magazynu );

ALTER TABLE asoscjacja_magazynu
    ADD CONSTRAINT relation_27_towar_fk FOREIGN KEY ( towar_id_produktu )
        REFERENCES towar ( id_produktu );

ALTER TABLE asocjacja_stanowiska
    ADD CONSTRAINT relation_5_pracownik_fk FOREIGN KEY ( pracownik_id_prac )
        REFERENCES pracownik ( id_prac );

ALTER TABLE asocjacja_stanowiska
    ADD CONSTRAINT relation_5_stanowisko_fk FOREIGN KEY ( stanowisko_id_stanowiska )
        REFERENCES stanowisko ( id_stanowiska );

ALTER TABLE "asocjacja podwladnego"
    ADD CONSTRAINT relation_6_pracownik_fk FOREIGN KEY ( pracownik_id_prac )
        REFERENCES pracownik ( id_prac );

ALTER TABLE "asocjacja podwladnego"
    ADD CONSTRAINT relation_6_pracownik_fkv1 FOREIGN KEY ( pracownik_id_prac1 )
        REFERENCES pracownik ( id_prac );

ALTER TABLE relation_7
    ADD CONSTRAINT relation_7_stanowisko_fk FOREIGN KEY ( stanowisko_id_stanowiska )
        REFERENCES stanowisko ( id_stanowiska );

ALTER TABLE relation_7
    ADD CONSTRAINT relation_7_uprawnienia_fk FOREIGN KEY ( uprawnienia_id_uprawnienia )
        REFERENCES uprawnienia ( id_uprawnienia );

ALTER TABLE assoscjacja_benefitu
    ADD CONSTRAINT relation_9_benefit_fk FOREIGN KEY ( benefit_id_benefitu )
        REFERENCES benefit ( id_benefitu );

ALTER TABLE assoscjacja_benefitu
    ADD CONSTRAINT relation_9_stanowisko_fk FOREIGN KEY ( stanowisko_id_stanowiska )
        REFERENCES stanowisko ( id_stanowiska );

ALTER TABLE rodzaj_towarow
    ADD CONSTRAINT rodzaj_towarow_produkt_fk FOREIGN KEY ( produkt_id_produktu )
        REFERENCES produkt ( id_produktu );

ALTER TABLE srodek_trwaly
    ADD CONSTRAINT srodek_trwaly_towar_fk FOREIGN KEY ( id_produktu )
        REFERENCES towar ( id_produktu );

ALTER TABLE towar
    ADD CONSTRAINT towar_produkt_fk FOREIGN KEY ( id_produktu )
        REFERENCES produkt ( id_produktu );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE umowa_pracownika
    ADD CONSTRAINT umowa_pracownika_zatrudnienie_fk FOREIGN KEY ( zatrudnienie_zatrudnienie_id )
        REFERENCES zatrudnienie ( zatrudnienie_id );

ALTER TABLE usluga
    ADD CONSTRAINT usluga_produkt_fk FOREIGN KEY ( id_produktu )
        REFERENCES produkt ( id_produktu );

ALTER TABLE zatrudnieniev1
    ADD CONSTRAINT zatrudnieniev1_pracownik_fk FOREIGN KEY ( pracownik_id_prac )
        REFERENCES pracownik ( id_prac );

ALTER TABLE zatrudnieniev1
    ADD CONSTRAINT zatrudnieniev1_zatrudnienie_fk FOREIGN KEY ( zatrudnienie_zatrudnienie_id )
        REFERENCES zatrudnienie ( zatrudnienie_id );

ALTER TABLE znajomosc_jezyka
    ADD CONSTRAINT znajomosc_jezyka_jezyk_fk FOREIGN KEY ( jezyk_id_jezyka )
        REFERENCES jezyk ( id_jezyka );

ALTER TABLE znajomosc_jezyka
    ADD CONSTRAINT znajomosc_jezyka_pracownik_fk FOREIGN KEY ( pracownik_id_prac )
        REFERENCES pracownik ( id_prac );

--  ERROR: No Discriminator Column found in Arc FKArc_9 - constraint trigger for Arc cannot be generated 

--  ERROR: No Discriminator Column found in Arc FKArc_9 - constraint trigger for Arc cannot be generated

CREATE SEQUENCE zatrudnienie_zatrudnienie_id START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER zatrudnienie_zatrudnienie_id BEFORE
    INSERT ON zatrudnienie
    FOR EACH ROW
    WHEN ( new.zatrudnienie_id IS NULL )
BEGIN
    :new.zatrudnienie_id := zatrudnienie_zatrudnienie_id.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            32
-- CREATE INDEX                             0
-- ALTER TABLE                             66
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           1
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          1
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                  12
-- WARNINGS                                 0
