-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-01-16 12:23:58 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE asocjacja_stanowiska (
    stanowisko_id_stanowiska NUMBER(10) NOT NULL,
    pracownik_id_prac        NUMBER(10) NOT NULL
);

ALTER TABLE asocjacja_stanowiska ADD CONSTRAINT relation_5_pk PRIMARY KEY ( stanowisko_id_stanowiska,
                                                                            pracownik_id_prac );

CREATE TABLE "asocjacja podwladnego" (
    pracownik_id_prac  NUMBER(10) NOT NULL,
    pracownik_id_prac1 NUMBER(10) NOT NULL
);

ALTER TABLE "asocjacja podwladnego" ADD CONSTRAINT relation_6_pk PRIMARY KEY ( pracownik_id_prac,
                                                                               pracownik_id_prac1 );

CREATE TABLE asoscjacja_magazynu (
    towar_id_produktu   NUMBER(10) NOT NULL,
    magazyn_id_magazynu NUMBER(10) NOT NULL
);

ALTER TABLE asoscjacja_magazynu ADD CONSTRAINT relation_27_pk PRIMARY KEY ( towar_id_produktu,
                                                                            magazyn_id_magazynu );

CREATE TABLE asoscjacja_placy (
    umowa_pracownika_id_umowy NUMBER(10) NOT NULL,
    p³aca_id_p³acy            NUMBER(12) NOT NULL
);

ALTER TABLE asoscjacja_placy ADD CONSTRAINT relation_17_pk PRIMARY KEY ( umowa_pracownika_id_umowy,
                                                                         p³aca_id_p³acy );

CREATE TABLE asoscjacja_poziomu_znajomosci ( 
--  ERROR: Column name length exceeds maximum allowed length(30) 
    poziom_znajomoœci_jêzyka_id_znajomosci_jêzyka NUMBER(10) NOT NULL,
    jêzyk_id_jezyka                               NUMBER(10) NOT NULL
);

ALTER TABLE asoscjacja_poziomu_znajomosci ADD CONSTRAINT relation_26_pk PRIMARY KEY ( poziom_znajomoœci_jêzyka_id_znajomosci_jêzyka,
                                                                                      jêzyk_id_jezyka );

CREATE TABLE asoscjacja_wyksztalcenia (
    pracownik_id_prac              NUMBER(10) NOT NULL,
    wykszta³cenie_id_wykszta³cenia NUMBER(10) NOT NULL
);

ALTER TABLE asoscjacja_wyksztalcenia ADD CONSTRAINT relation_1_pk PRIMARY KEY ( pracownik_id_prac,
                                                                                wykszta³cenie_id_wykszta³cenia );

CREATE TABLE assoscjacja_benefitu (
    stanowisko_id_stanowiska NUMBER(10) NOT NULL,
    benefit_id_benefitu      NUMBER(10) NOT NULL
);

ALTER TABLE assoscjacja_benefitu ADD CONSTRAINT relation_9_pk PRIMARY KEY ( stanowisko_id_stanowiska,
                                                                            benefit_id_benefitu );

CREATE TABLE benefit (
    id_benefitu NUMBER(10) NOT NULL,
    nazwa       VARCHAR2(50) NOT NULL,
    koszt       NUMBER(10, 2) NOT NULL,
    poziom      VARCHAR2(50)
);

ALTER TABLE benefit ADD CONSTRAINT benefit_pk PRIMARY KEY ( id_benefitu );

CREATE TABLE dzia³ (
    id_dzia³u               NUMBER(10) NOT NULL,
    nazwa                   VARCHAR2(50) NOT NULL,
    adres                   VARCHAR2(100) NOT NULL,
    kirownik_dzia³u_id_prac NUMBER(10) NOT NULL
);

ALTER TABLE dzia³ ADD CONSTRAINT dzia³_pk PRIMARY KEY ( id_dzia³u );

CREATE TABLE faktura (
    id_faktury                            NUMBER(10) NOT NULL,
    data_wystawienia_faktury              DATE NOT NULL,
    data_p³atnoœci                        DATE NOT NULL,
    typ_faktury                           VARCHAR2(50) NOT NULL,
    rodzaj_p³atnoœci                      VARCHAR2(100) NOT NULL,
    wartoœæ_netto                         NUMBER(10, 2) NOT NULL,
    wartoœæ_brutto                        NUMBER(10, 2) NOT NULL,
    kontrachent_id_kontrachenta           NUMBER(10),
    pracownik_id_prac                     NUMBER(10) NOT NULL, 
--  ERROR: Column name length exceeds maximum allowed length(30) 
    ksiêga_przychodu_i_rozchodu_id_ksiêgi NUMBER(10)
);

ALTER TABLE faktura ADD CONSTRAINT faktura_pk PRIMARY KEY ( id_faktury );

CREATE TABLE jêzyk (
    id_jezyka NUMBER(10) NOT NULL,
    nazwa     VARCHAR2(50) NOT NULL,
    podtyp    VARCHAR2(50)
);

ALTER TABLE jêzyk ADD CONSTRAINT jêzyk_pk PRIMARY KEY ( id_jezyka );

CREATE TABLE kirownik_dzia³u (
    id_prac                      NUMBER(10) NOT NULL,
    numer_telefonu_stacjonarnego VARCHAR2(20) NOT NULL
);

ALTER TABLE kirownik_dzia³u ADD CONSTRAINT kirownik_dzia³u_pk PRIMARY KEY ( id_prac );

CREATE TABLE kontrachent (
    id_kontrachenta         NUMBER(10) NOT NULL,
    nazwa                   VARCHAR2(200) NOT NULL,
    adres_siedziby          VARCHAR2(100) NOT NULL,
    nip                     NUMBER(12) NOT NULL,
    adres_do_korespondencji VARCHAR2(100) NOT NULL,
    czy_czynny_podatnik_vat CHAR(1) NOT NULL
);

ALTER TABLE kontrachent ADD CONSTRAINT kontrachent_pk PRIMARY KEY ( id_kontrachenta );

CREATE TABLE koszt_zus (
    id_kosztu_zus      NUMBER(10) NOT NULL,
    okres              VARCHAR2(100) NOT NULL,
    sk³adka_zdrowotna  NUMBER(10, 2) NOT NULL,
    sk³adka_emerytalna NUMBER(10, 2) NOT NULL,
    sk³adka_rentowa    NUMBER(10, 2) NOT NULL,
    sk³adka_chorobowa  NUMBER(10, 2) NOT NULL,
    sk³adka_wypadkowa  NUMBER(10, 2) NOT NULL,
    fundusz_pracy      NUMBER(10, 2) NOT NULL
);

ALTER TABLE koszt_zus ADD CONSTRAINT koszt_zus_pk PRIMARY KEY ( id_kosztu_zus );

CREATE TABLE ksiêga_przychodu_i_rozchodu (
    id_ksiêgi               NUMBER(10) NOT NULL,
    okres                   VARCHAR2(100) NOT NULL,
    data_stworzenia         DATE NOT NULL,
    kto_stworzy³            VARCHAR2(50) NOT NULL,
    koszt_zus_id_kosztu_zus NUMBER(10) NOT NULL
);

ALTER TABLE ksiêga_przychodu_i_rozchodu ADD CONSTRAINT ksiêga_przychodu_i_rozchodu_pk PRIMARY KEY ( id_ksiêgi );

CREATE TABLE magazyn (
    id_magazynu NUMBER(10) NOT NULL,
    nazwa       VARCHAR2(50) NOT NULL,
    adres       VARCHAR2(200) NOT NULL
);

ALTER TABLE magazyn ADD CONSTRAINT magazyn_pk PRIMARY KEY ( id_magazynu );

CREATE TABLE p³aca (
    id_p³acy                              NUMBER(12) NOT NULL,
    liczba_przepracowanych_godzin         NUMBER(10) NOT NULL,
    dodatki                               NUMBER(10, 2),
    nadgodziny                            NUMBER(10),
    ostateczna_kwota                      NUMBER(10, 2) NOT NULL, 
--  ERROR: Column name length exceeds maximum allowed length(30) 
    ksiêga_przychodu_i_rozchodu_id_ksiêgi NUMBER(10)
);

ALTER TABLE p³aca ADD CONSTRAINT p³aca_pk PRIMARY KEY ( id_p³acy );

CREATE TABLE poziom_znajomoœci_jêzyka (
    id_znajomosci_jêzyka NUMBER(10) NOT NULL,
    nazwa                VARCHAR2(50)
);

ALTER TABLE poziom_znajomoœci_jêzyka ADD CONSTRAINT poziom_znajomoœci_jêzyka_pk PRIMARY KEY ( id_znajomosci_jêzyka );

CREATE TABLE pracownik (
    id_prac               NUMBER(10) NOT NULL,
    imie                  VARCHAR2(50) NOT NULL,
    nazwisko              VARCHAR2(50) NOT NULL,
    data_urodzenia        DATE NOT NULL,
    pesel                 NUMBER(11),
    p³eæ                  VARCHAR2(2),
    drugie_imie           VARCHAR2(50),
    nazwisko_rodowe       VARCHAR2(50),
    numer_konta_bankowego NUMBER(50),
    dzia³_id_dzia³u       NUMBER(10) NOT NULL,
    adres                 VARCHAR2(100)
);

ALTER TABLE pracownik ADD CONSTRAINT pracownik_pk PRIMARY KEY ( id_prac );

CREATE TABLE produkt (
    id_produktu        NUMBER(10) NOT NULL,
    nazwa              VARCHAR2(100) NOT NULL,
    cena_netto         NUMBER(10, 2) NOT NULL,
    faktura_id_faktury NUMBER(10) NOT NULL
);

ALTER TABLE produkt ADD CONSTRAINT produkt_pk PRIMARY KEY ( id_produktu );

CREATE TABLE relation_7 (
    stanowisko_id_stanowiska   NUMBER(10) NOT NULL,
    uprawnienia_id_uprawnienia NUMBER(10) NOT NULL
);

ALTER TABLE relation_7 ADD CONSTRAINT relation_7_pk PRIMARY KEY ( stanowisko_id_stanowiska,
                                                                  uprawnienia_id_uprawnienia );

CREATE TABLE rodzaj_towarów (
    id_rodzaju_towaru   NUMBER(10) NOT NULL,
    nazwa               VARCHAR2(100) NOT NULL,
    stawka_vat          NUMBER(10, 2) NOT NULL,
    produkt_id_produktu NUMBER(10) NOT NULL
);

ALTER TABLE rodzaj_towarów ADD CONSTRAINT rodzaj_towarów_pk PRIMARY KEY ( id_rodzaju_towaru,
                                                                          stawka_vat );

CREATE TABLE stanowisko (
    id_stanowiska NUMBER(10) NOT NULL,
    nazwa         VARCHAR2(50) NOT NULL
);

ALTER TABLE stanowisko ADD CONSTRAINT stanowisko_pk PRIMARY KEY ( id_stanowiska );

CREATE TABLE œrodek_trwa³y (
    id_produktu        NUMBER(10) NOT NULL,
    stawka_amortyzacji VARCHAR2(100)
);

ALTER TABLE œrodek_trwa³y ADD CONSTRAINT œrodek_trwa³y_pk PRIMARY KEY ( id_produktu );

CREATE TABLE towar (
    id_produktu                                   NUMBER(10) NOT NULL,
    data_przyjêcia_na_stan                        DATE,
    data_zbycia                                   DATE, 
--  ERROR: Column name length exceeds maximum allowed length(30) 
    czy_wrzucamy_go_do_ewidencji_œrodków_trwa³ych CHAR(1)
);

ALTER TABLE towar ADD CONSTRAINT towar_pk PRIMARY KEY ( id_produktu );

CREATE TABLE umowa_pracownika (
    id_umowy                     NUMBER(10) NOT NULL,
    rodzaj_umowy                 VARCHAR2(50) NOT NULL,
    data_zawarcia                DATE NOT NULL,
    data_zakoñczenia             DATE,
    rodzaj_zatrudnienia          VARCHAR2(50) NOT NULL,
    wielkoœc_etatu               VARCHAR2(50) NOT NULL,
    stawka_godzinowa             NUMBER(10, 2),
    zatrudnienie_zatrudnienie_id NUMBER NOT NULL
);

ALTER TABLE umowa_pracownika ADD CONSTRAINT umowa_pracownika_pk PRIMARY KEY ( id_umowy );

CREATE TABLE uprawnienia (
    id_uprawnienia NUMBER(10) NOT NULL,
    nazwa          VARCHAR2(50) NOT NULL
);

ALTER TABLE uprawnienia ADD CONSTRAINT uprawnienia_pk PRIMARY KEY ( id_uprawnienia );

CREATE TABLE us³uga (
    id_produktu        NUMBER(10) NOT NULL,
    data_zrealizowania DATE
);

ALTER TABLE us³uga ADD CONSTRAINT us³uga_pk PRIMARY KEY ( id_produktu );

CREATE TABLE wykszta³cenie (
    id_wykszta³cenia NUMBER(10) NOT NULL,
    poziom           VARCHAR2(50) NOT NULL,
    nazwa            VARCHAR2(100) NOT NULL,
    data_uzyskania   DATE NOT NULL,
    ukoñczona_szkola VARCHAR2(100) NOT NULL,
    podtyp           VARCHAR2(100)
);

ALTER TABLE wykszta³cenie ADD CONSTRAINT wykszta³cenie_pk PRIMARY KEY ( id_wykszta³cenia );

CREATE TABLE zatrudnienie (
    data_rozpoczêcia DATE NOT NULL,
    data_zakoñczenia DATE,
    zatrudnienie_id  NUMBER NOT NULL
);

ALTER TABLE zatrudnienie ADD CONSTRAINT zatrudnienie_pk PRIMARY KEY ( zatrudnienie_id );

CREATE TABLE zatrudnieniev1 (
    pracownik_id_prac            NUMBER(10) NOT NULL,
    zatrudnienie_zatrudnienie_id NUMBER NOT NULL
);

ALTER TABLE zatrudnieniev1 ADD CONSTRAINT zatrudnieniev1_pk PRIMARY KEY ( pracownik_id_prac,
                                                                          zatrudnienie_zatrudnienie_id );

CREATE TABLE znajomoœæ_jezyka (
    pracownik_id_prac NUMBER(10) NOT NULL,
    jêzyk_id_jezyka   NUMBER(10) NOT NULL
);

ALTER TABLE znajomoœæ_jezyka ADD CONSTRAINT znajomoœæ_jezyka_pk PRIMARY KEY ( pracownik_id_prac,
                                                                              jêzyk_id_jezyka );

ALTER TABLE dzia³
    ADD CONSTRAINT dzia³_kirownik_dzia³u_fk FOREIGN KEY ( kirownik_dzia³u_id_prac )
        REFERENCES kirownik_dzia³u ( id_prac );

ALTER TABLE faktura
    ADD CONSTRAINT faktura_kontrachent_fk FOREIGN KEY ( kontrachent_id_kontrachenta )
        REFERENCES kontrachent ( id_kontrachenta );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE faktura
    ADD CONSTRAINT faktura_ksiêga_przychodu_i_rozchodu_fk FOREIGN KEY ( ksiêga_przychodu_i_rozchodu_id_ksiêgi )
        REFERENCES ksiêga_przychodu_i_rozchodu ( id_ksiêgi );

ALTER TABLE faktura
    ADD CONSTRAINT faktura_pracownik_fk FOREIGN KEY ( pracownik_id_prac )
        REFERENCES pracownik ( id_prac );

ALTER TABLE kirownik_dzia³u
    ADD CONSTRAINT kirownik_dzia³u_pracownik_fk FOREIGN KEY ( id_prac )
        REFERENCES pracownik ( id_prac );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE ksiêga_przychodu_i_rozchodu
    ADD CONSTRAINT ksiêga_przychodu_i_rozchodu_koszt_zus_fk FOREIGN KEY ( koszt_zus_id_kosztu_zus )
        REFERENCES koszt_zus ( id_kosztu_zus );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE p³aca
    ADD CONSTRAINT p³aca_ksiêga_przychodu_i_rozchodu_fk FOREIGN KEY ( ksiêga_przychodu_i_rozchodu_id_ksiêgi )
        REFERENCES ksiêga_przychodu_i_rozchodu ( id_ksiêgi );

ALTER TABLE pracownik
    ADD CONSTRAINT pracownik_dzia³_fk FOREIGN KEY ( dzia³_id_dzia³u )
        REFERENCES dzia³ ( id_dzia³u );

ALTER TABLE produkt
    ADD CONSTRAINT produkt_faktura_fk FOREIGN KEY ( faktura_id_faktury )
        REFERENCES faktura ( id_faktury );

ALTER TABLE asoscjacja_wyksztalcenia
    ADD CONSTRAINT relation_1_pracownik_fk FOREIGN KEY ( pracownik_id_prac )
        REFERENCES pracownik ( id_prac );

ALTER TABLE asoscjacja_wyksztalcenia
    ADD CONSTRAINT relation_1_wykszta³cenie_fk FOREIGN KEY ( wykszta³cenie_id_wykszta³cenia )
        REFERENCES wykszta³cenie ( id_wykszta³cenia );

ALTER TABLE asoscjacja_placy
    ADD CONSTRAINT relation_17_p³aca_fk FOREIGN KEY ( p³aca_id_p³acy )
        REFERENCES p³aca ( id_p³acy );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE asoscjacja_placy
    ADD CONSTRAINT relation_17_umowa_pracownika_fk FOREIGN KEY ( umowa_pracownika_id_umowy )
        REFERENCES umowa_pracownika ( id_umowy );

ALTER TABLE asoscjacja_poziomu_znajomosci
    ADD CONSTRAINT relation_26_jêzyk_fk FOREIGN KEY ( jêzyk_id_jezyka )
        REFERENCES jêzyk ( id_jezyka );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE asoscjacja_poziomu_znajomosci
    ADD CONSTRAINT relation_26_poziom_znajomoœci_jêzyka_fk FOREIGN KEY ( poziom_znajomoœci_jêzyka_id_znajomosci_jêzyka )
        REFERENCES poziom_znajomoœci_jêzyka ( id_znajomosci_jêzyka );

ALTER TABLE asoscjacja_magazynu
    ADD CONSTRAINT relation_27_magazyn_fk FOREIGN KEY ( magazyn_id_magazynu )
        REFERENCES magazyn ( id_magazynu );

ALTER TABLE asoscjacja_magazynu
    ADD CONSTRAINT relation_27_towar_fk FOREIGN KEY ( towar_id_produktu )
        REFERENCES towar ( id_produktu );

ALTER TABLE asocjacja_stanowiska
    ADD CONSTRAINT relation_5_pracownik_fk FOREIGN KEY ( pracownik_id_prac )
        REFERENCES pracownik ( id_prac );

ALTER TABLE asocjacja_stanowiska
    ADD CONSTRAINT relation_5_stanowisko_fk FOREIGN KEY ( stanowisko_id_stanowiska )
        REFERENCES stanowisko ( id_stanowiska );

ALTER TABLE "asocjacja podwladnego"
    ADD CONSTRAINT relation_6_pracownik_fk FOREIGN KEY ( pracownik_id_prac )
        REFERENCES pracownik ( id_prac );

ALTER TABLE "asocjacja podwladnego"
    ADD CONSTRAINT relation_6_pracownik_fkv1 FOREIGN KEY ( pracownik_id_prac1 )
        REFERENCES pracownik ( id_prac );

ALTER TABLE relation_7
    ADD CONSTRAINT relation_7_stanowisko_fk FOREIGN KEY ( stanowisko_id_stanowiska )
        REFERENCES stanowisko ( id_stanowiska );

ALTER TABLE relation_7
    ADD CONSTRAINT relation_7_uprawnienia_fk FOREIGN KEY ( uprawnienia_id_uprawnienia )
        REFERENCES uprawnienia ( id_uprawnienia );

ALTER TABLE assoscjacja_benefitu
    ADD CONSTRAINT relation_9_benefit_fk FOREIGN KEY ( benefit_id_benefitu )
        REFERENCES benefit ( id_benefitu );

ALTER TABLE assoscjacja_benefitu
    ADD CONSTRAINT relation_9_stanowisko_fk FOREIGN KEY ( stanowisko_id_stanowiska )
        REFERENCES stanowisko ( id_stanowiska );

ALTER TABLE rodzaj_towarów
    ADD CONSTRAINT rodzaj_towarów_produkt_fk FOREIGN KEY ( produkt_id_produktu )
        REFERENCES produkt ( id_produktu );

ALTER TABLE œrodek_trwa³y
    ADD CONSTRAINT œrodek_trwa³y_towar_fk FOREIGN KEY ( id_produktu )
        REFERENCES towar ( id_produktu );

ALTER TABLE towar
    ADD CONSTRAINT towar_produkt_fk FOREIGN KEY ( id_produktu )
        REFERENCES produkt ( id_produktu );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE umowa_pracownika
    ADD CONSTRAINT umowa_pracownika_zatrudnienie_fk FOREIGN KEY ( zatrudnienie_zatrudnienie_id )
        REFERENCES zatrudnienie ( zatrudnienie_id );

ALTER TABLE us³uga
    ADD CONSTRAINT us³uga_produkt_fk FOREIGN KEY ( id_produktu )
        REFERENCES produkt ( id_produktu );

ALTER TABLE zatrudnieniev1
    ADD CONSTRAINT zatrudnieniev1_pracownik_fk FOREIGN KEY ( pracownik_id_prac )
        REFERENCES pracownik ( id_prac );

ALTER TABLE zatrudnieniev1
    ADD CONSTRAINT zatrudnieniev1_zatrudnienie_fk FOREIGN KEY ( zatrudnienie_zatrudnienie_id )
        REFERENCES zatrudnienie ( zatrudnienie_id );

ALTER TABLE znajomoœæ_jezyka
    ADD CONSTRAINT znajomoœæ_jezyka_jêzyk_fk FOREIGN KEY ( jêzyk_id_jezyka )
        REFERENCES jêzyk ( id_jezyka );

ALTER TABLE znajomoœæ_jezyka
    ADD CONSTRAINT znajomoœæ_jezyka_pracownik_fk FOREIGN KEY ( pracownik_id_prac )
        REFERENCES pracownik ( id_prac );

--  ERROR: No Discriminator Column found in Arc FKArc_9 - constraint trigger for Arc cannot be generated 

--  ERROR: No Discriminator Column found in Arc FKArc_9 - constraint trigger for Arc cannot be generated

CREATE SEQUENCE zatrudnienie_zatrudnienie_id START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER zatrudnienie_zatrudnienie_id BEFORE
    INSERT ON zatrudnienie
    FOR EACH ROW
    WHEN ( new.zatrudnienie_id IS NULL )
BEGIN
    :new.zatrudnienie_id := zatrudnienie_zatrudnienie_id.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            32
-- CREATE INDEX                             0
-- ALTER TABLE                             66
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           1
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          1
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                  12
-- WARNINGS                                 0
